let DATA=null;grist.ready({requiredAccess:"full"});document.addEventListener("DOMContentLoaded",()=>{document.getElementById("addScenarioBtn").onclick=addScenario;document.getElementById("addDomainBtn").onclick=addDomain;document.getElementById("duplicateBtn").onclick=duplicateScenario;refreshAdmin()});
async function refreshAdmin(){const st=document.getElementById("status");try{st.textContent="Chargement des référentiels…";st.classList.remove("error");DATA=await loadAll();renderScenarios();renderTariffs();renderDomainsAdmin();populateDuplicate();st.textContent="Référentiels synchronisés avec Grist."}catch(e){console.error(e);st.textContent="Erreur Grist : "+e.message;st.classList.add("error")}}
function editable(value,type,field,rowId,table,extra=""){const val=type==="checkbox"?"":`value="${esc(value??"")}"`,checked=type==="checkbox"&&value?"checked":"";return`<input class="admin-table-input" type="${type}" ${val} ${checked} ${extra} data-table="${table}" data-row="${rowId}" data-field="${field}">`}function actionCell(t,id){return`<div class="admin-actions"><button class="tiny-btn save-row" data-table="${t}" data-row="${id}">Enregistrer</button><button class="tiny-btn danger delete-row" data-table="${t}" data-row="${id}">Supprimer</button></div>`}
function renderScenarios(){const b=document.getElementById("scenarioAdminBody");b.innerHTML=DATA.scenarios.map(s=>`<tr><td>${editable(s.Nom,"text","Nom",s.id,TABLES.scenarios)}</td><td>${editable(s.Annee,"number","Annee",s.id,TABLES.scenarios,'min="2020"')}</td><td>${editable(s.Nb_Mois,"number","Nb_Mois",s.id,TABLES.scenarios,'min="1" max="36"')}</td><td>${editable(s.Taux_USD_EUR,"number","Taux_USD_EUR",s.id,TABLES.scenarios,'step="0.0001"')}</td><td>${editable(s.Taux_Utilisation,"number","Taux_Utilisation",s.id,TABLES.scenarios,'step="0.05" min="0" max="1"')}</td><td>${editable(s.Statut,"text","Statut",s.id,TABLES.scenarios)}</td><td>${actionCell(TABLES.scenarios,s.id)}</td></tr>`).join("");bindRows(b)}
function renderTariffs(){const b=document.getElementById("tariffAdminBody");b.innerHTML=DATA.tariffs.map(t=>`<tr><td><b>${esc(t.Offre)}</b></td><td>${esc(t.Type_Cout)}</td><td>${editable(t.Prix_Annuel_Siege,"number","Prix_Annuel_Siege",t.id,TABLES.tariffs,'min="0"')}</td><td>${editable(t.Prix_Mensuel,"number","Prix_Mensuel",t.id,TABLES.tariffs,'min="0"')}</td><td>${editable(t.Actif,"checkbox","Actif",t.id,TABLES.tariffs)}</td><td>${actionCell(TABLES.tariffs,t.id)}</td></tr>`).join("");bindRows(b)}
function renderDomainsAdmin(){const b=document.getElementById("domainAdminBody");b.innerHTML=DATA.domains.map(d=>`<tr><td>${editable(d.Nom,"text","Nom",d.id,TABLES.domains)}</td><td>${editable(d.Actif,"checkbox","Actif",d.id,TABLES.domains)}</td><td>${editable(d.Responsable||"","text","Responsable",d.id,TABLES.domains)}</td><td>${actionCell(TABLES.domains,d.id)}</td></tr>`).join("");bindRows(b)}
function bindRows(root){root.querySelectorAll(".save-row").forEach(b=>b.onclick=()=>saveRow(b.dataset.table,Number(b.dataset.row),b.closest("tr")));root.querySelectorAll(".delete-row").forEach(b=>b.onclick=()=>deleteRow(b.dataset.table,Number(b.dataset.row)))}
async function saveRow(table,rowId,tr){const fields={};tr.querySelectorAll("input[data-field]").forEach(i=>{let v=i.type==="checkbox"?i.checked:i.value;if(i.type==="number")v=Number(v||0);fields[i.dataset.field]=v});try{await updateRecord(table,rowId,fields);showToast("Modifications enregistrées.");await refreshAdmin()}catch(e){showToast("Erreur : "+e.message,true)}}
async function deleteRow(table,rowId){if(!confirm("Supprimer cet enregistrement ?"))return;try{await removeRecord(table,rowId);showToast("Enregistrement supprimé.");await refreshAdmin()}catch(e){showToast("Suppression impossible : "+e.message,true)}}
async function addScenario(){try{await addRecord(TABLES.scenarios,{Nom:"Nouveau scénario",Annee:new Date().getFullYear(),Nb_Mois:12,Taux_USD_EUR:.86,Taux_Utilisation:1,Statut:"Travail",Commentaire:""});await refreshAdmin();showToast("Nouveau scénario créé.")}catch(e){showToast("Erreur : "+e.message,true)}}
async function addDomain(){try{await addRecord(TABLES.domains,{Nom:"Nouveau domaine",Actif:true,Responsable:""});await refreshAdmin();showToast("Nouveau domaine créé.")}catch(e){showToast("Erreur : "+e.message,true)}}
function populateDuplicate(){const s=document.getElementById("duplicateSource");s.innerHTML=DATA.scenarios.map(x=>`<option value="${x.id}">${esc(x.Nom)}</option>`).join("");const src=DATA.scenarios[0];if(src){document.getElementById("duplicateYear").value=src.Annee;document.getElementById("duplicateMonths").value=src.Nb_Mois}s.onchange=()=>{const x=DATA.scenarioById[Number(s.value)];if(x){document.getElementById("duplicateYear").value=x.Annee;document.getElementById("duplicateMonths").value=x.Nb_Mois}}}
async function duplicateScenario(){const sourceId=Number(document.getElementById("duplicateSource").value),source=DATA.scenarioById[sourceId],name=document.getElementById("duplicateName").value.trim();if(!source||!name)return showToast("Indique un nom pour le nouveau scénario.",true);try{await grist.docApi.applyUserActions([["AddRecord",TABLES.scenarios,null,{Nom:name,Annee:Number(document.getElementById("duplicateYear").value||source.Annee),Nb_Mois:Number(document.getElementById("duplicateMonths").value||source.Nb_Mois),Taux_USD_EUR:Number(source.Taux_USD_EUR||0),Taux_Utilisation:Number(source.Taux_Utilisation||1),Statut:"Travail",Commentaire:`Copie de ${source.Nom}`}]]);await refreshAdmin();const ns=DATA.scenarios.find(s=>s.Nom===name);if(!ns)throw new Error("Le nouveau scénario n'a pas pu être retrouvé.");const actions=[];DATA.enterprise.filter(r=>Number(r.Scenario)===sourceId).forEach(r=>actions.push(["AddRecord",TABLES.enterprise,null,{Scenario:ns.id,Domaine:r.Domaine,Nb_Sieges:Number(r.Nb_Sieges||0),Budget_Usage_User_Mois:Number(r.Budget_Usage_User_Mois||0)}]));DATA.individual.filter(r=>Number(r.Scenario)===sourceId).forEach(r=>actions.push(["AddRecord",TABLES.individual,null,{Scenario:ns.id,Domaine:r.Domaine,Offre:r.Offre,Nb_Utilisateurs:Number(r.Nb_Utilisateurs||0)}]));if(actions.length)await grist.docApi.applyUserActions(actions);await refreshAdmin();document.getElementById("duplicateName").value="";showToast("Scénario dupliqué avec ses allocations.")}catch(e){console.error(e);showToast("Erreur de duplication : "+e.message,true)}}
