const T={domains:'Domaines',scenarios:'Scenarios',tariffs:'Tarifs',enterprise:'Enterprise',individual:'Forfaits_Individuels',rights:'Droits_Utilisateurs'};
const COLORS={'Enterprise - Sièges':'#2f6fed','Enterprise - Usage':'#24b89a','Pro':'#7c4de8','Max5x':'#e7a62c','Max20x':'#dc4c5a'};
let D=null,ACCESS={role:'DENIED',domainIds:[]},CURRENT=null,DIRTY=new Map();
grist.ready({requiredAccess:'full'});
document.addEventListener('DOMContentLoaded',boot);
function rows(t){if(!t||!Array.isArray(t.id))return[];return t.id.map((id,i)=>{const r={id};for(const[k,v]of Object.entries(t))if(k!=='id'&&Array.isArray(v))r[k]=v[i];return r})}
function money(v,c='USD'){return new Intl.NumberFormat('fr-FR',{style:'currency',currency:c,maximumFractionDigits:0}).format(Number(v||0))}
function num(v){return new Intl.NumberFormat('fr-FR',{maximumFractionDigits:0}).format(Number(v||0))}
function pct(v){return new Intl.NumberFormat('fr-FR',{style:'percent',maximumFractionDigits:1}).format(Number(v||0))}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function toast(m,e=false){const x=document.getElementById('toast');x.textContent=m;x.className='toast show'+(e?' error':'');setTimeout(()=>x.className='toast',2200)}
async function fetchAll(){const names=Object.values(T);const vals=await Promise.all(names.map(n=>grist.docApi.fetchTable(n).catch(()=>({id:[]}))));const o={};names.forEach((n,i)=>o[n]=rows(vals[i]));o.domainById=Object.fromEntries(o[T.domains].map(r=>[r.id,r]));o.scenarioById=Object.fromEntries(o[T.scenarios].map(r=>[r.id,r]));o.tariffById=Object.fromEntries(o[T.tariffs].map(r=>[r.id,r]));return o}
async function boot(){try{D=await fetchAll();deriveAccess();renderShell()}catch(e){document.getElementById('root').innerHTML='<div class="denied"><div class="denied-card"><div class="denied-top"></div><div class="lock">🔒</div><h1>Erreur de chargement</h1><p>'+esc(e.message)+'</p></div></div>'}}
function deriveAccess(){const rights=D[T.rights].filter(r=>r.Actif!==false);if(rights.some(r=>String(r.Role_App).toLowerCase()==='admin')){ACCESS={role:'OWNER',domainIds:D[T.domains].map(d=>Number(d.id)),rights};return}if(rights.length){ACCESS={role:'DOMAIN_USER',domainIds:[...new Set(rights.map(r=>Number(r.Domaine)).filter(Boolean))],rights};return}const entDomains=[...new Set(D[T.enterprise].map(r=>Number(r.Domaine)).filter(Boolean))];if(D[T.domains].length>1&&entDomains.length>1){ACCESS={role:'OWNER',domainIds:D[T.domains].map(d=>Number(d.id)),rights:[]};return}ACCESS={role:'DENIED',domainIds:[]}}
function renderShell(){if(ACCESS.role==='DENIED'){document.getElementById('root').innerHTML=`<div class="denied"><div class="denied-card"><div class="denied-top"></div><div class="lock">🔒</div><h1>Accès non autorisé</h1><p>Vous ne disposez pas des droits nécessaires pour accéder à ce module.</p><p>Si vous pensez devoir disposer de cet accès, veuillez contacter l’administrateur de la solution.</p><div class="denied-note">Votre administrateur pourra vérifier et, si nécessaire, mettre à jour vos droits d’accès.</div></div></div>`;return}
const admin=ACCESS.role==='OWNER';document.getElementById('root').innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">◫</div><div><div class="brand-title">FINOPS CLAUDE</div><div class="brand-sub">AP-HP · I&D</div></div></div><nav class="nav"><button class="active" data-view="dashboard">◧ Dashboard</button><button data-view="simulation">⌘ Simulation</button>${admin?'<button data-view="scenarios">▤ Scénarios</button><button data-view="tariffs">¤ Tarifs & offres</button><button data-view="domains">◎ Domaines</button><button data-view="rights">♙ Droits utilisateurs</button>':''}</nav><div class="sidebar-footer" id="userBadge"></div></aside><main class="content"><header class="header"><div><h1 id="pageTitle">Dashboard</h1><div class="scope" id="scope"></div></div><div class="controls"><label>Scénario<select id="scenarioSelect"></select></label><button id="refreshBtn" class="btn secondary">Actualiser</button></div></header><div class="status" id="status">Données synchronisées avec Grist.</div><section id="view-dashboard" class="view active"><div class="kpis" id="kpis"></div><div class="grid2"><article class="card"><h3>Budget par offre</h3><div class="donut-layout" id="offerDonut"></div></article><article class="card"><h3>Budget par domaine</h3><div id="domainBars"></div></article></div><article class="card"><h3>Vue budgétaire détaillée</h3><div class="table-wrap"><table><thead><tr><th>Domaine</th><th>Enterprise sièges</th><th>Enterprise usage</th><th>Pro</th><th>Max 5x</th><th>Max 20x</th><th>Total USD</th><th>Total EUR</th></tr></thead><tbody id="budgetMatrix"></tbody></table></div></article></section><section id="view-simulation" class="view"><article class="card"><div class="card-head"><div><h3>Simulation</h3><p>Les modifications sont enregistrées directement dans Grist.</p></div><button id="saveSimulationBtn" class="btn primary">Enregistrer</button></div><div class="table-wrap"><table><thead><tr><th>Domaine</th><th>Enterprise</th><th>Usage/user/mois ($)</th><th>Pro</th><th>Max 5x</th><th>Max 20x</th><th>Total</th></tr></thead><tbody id="simulationBody"></tbody></table></div></article></section>${admin?'<section id="view-scenarios" class="view"></section><section id="view-tariffs" class="view"></section><section id="view-domains" class="view"></section><section id="view-rights" class="view"></section>':''}</main></div>`;
wireShell();populateScenarios();renderAll();if(admin)renderAdmin()}
function wireShell(){document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>switchView(b.dataset.view));document.getElementById('refreshBtn').onclick=boot;document.getElementById('scenarioSelect').onchange=renderAll;document.getElementById('saveSimulationBtn').onclick=saveSimulation}
function switchView(v){document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.getElementById('view-'+v).classList.add('active');document.getElementById('pageTitle').textContent={dashboard:'Dashboard',simulation:'Simulation',scenarios:'Scénarios',tariffs:'Tarifs & offres',domains:'Domaines',rights:'Droits utilisateurs'}[v]}
function scopedDomains(){return D[T.domains].filter(d=>d.Actif!==false&&ACCESS.domainIds.includes(Number(d.id)))}
function scopedEnterprise(sid){return D[T.enterprise].filter(r=>Number(r.Scenario)===Number(sid)&&ACCESS.domainIds.includes(Number(r.Domaine)))}
function scopedIndividual(sid){return D[T.individual].filter(r=>Number(r.Scenario)===Number(sid)&&ACCESS.domainIds.includes(Number(r.Domaine)))}
function populateScenarios(){const s=document.getElementById('scenarioSelect');s.innerHTML=D[T.scenarios].map(x=>`<option value="${x.id}">${esc(x.Nom)}</option>`).join('')}
function selectedScenario(){return D.scenarioById[Number(document.getElementById('scenarioSelect').value)]}
function model(){const s=selectedScenario(),ers=scopedEnterprise(s.id),irs=scopedIndividual(s.id),bd={};for(const d of scopedDomains())bd[d.id]={d,eu:0,seat:0,usage:0,Pro:0,Max5x:0,Max20x:0,pu:0,m5u:0,m20u:0,total:0};let eu=0,seat=0,usage=0;for(const r of ers){const x=bd[r.Domaine];if(!x)continue;x.eu+=+r.Nb_Sieges||0;x.seat+=+r.Cout_Sieges||0;x.usage+=+r.Usage_Estime||0;eu+=+r.Nb_Sieges||0;seat+=+r.Cout_Sieges||0;usage+=+r.Usage_Estime||0}const pb={Pro:0,Max5x:0,Max20x:0},pu={Pro:0,Max5x:0,Max20x:0};for(const r of irs){const t=D.tariffById[r.Offre],x=bd[r.Domaine];if(!t||!x||!(t.Offre in pb))continue;const b=+r.Budget_USD||0,u=+r.Nb_Utilisateurs||0;pb[t.Offre]+=b;pu[t.Offre]+=u;x[t.Offre]+=b;if(t.Offre==='Pro')x.pu+=u;if(t.Offre==='Max5x')x.m5u+=u;if(t.Offre==='Max20x')x.m20u+=u}Object.values(bd).forEach(x=>x.total=x.seat+x.usage+x.Pro+x.Max5x+x.Max20x);const individual=pb.Pro+pb.Max5x+pb.Max20x,total=seat+usage+individual,rate=+s.Taux_USD_EUR||0;return{s,ers,irs,bd,eu,seat,usage,pb,pu,individual,total,rate}}
function renderAll(){CURRENT=model();const names=scopedDomains().map(d=>d.Nom).join(', ');document.getElementById('scope').textContent=ACCESS.role==='OWNER'?'Périmètre : tous les domaines':`Périmètre : ${names}`;document.getElementById('userBadge').innerHTML=`<b>${ACCESS.role==='OWNER'?'Owner / Admin':'Utilisateur domaine'}</b><br>${esc(names||'Tous les domaines')}`;renderKpis();renderOffers();renderBars();renderMatrix();renderSimulation()}
function renderKpis(){const m=CURRENT;document.getElementById('kpis').innerHTML=[[num(m.eu),'Utilisateurs Enterprise'],[money(m.seat),'Coût sièges Enterprise'],[money(m.usage),'Usage Enterprise estimé'],[money(m.individual),'Forfaits individuels'],[money(m.total),'Budget total USD'],[money(m.total*m.rate,'EUR'),'Budget total EUR']].map(x=>`<div class="kpi"><div class="v">${x[0]}</div><div class="l">${x[1]}</div></div>`).join('')}
function offerRows(){const m=CURRENT;return[{n:'Enterprise - Sièges',v:m.seat},{n:'Enterprise - Usage',v:m.usage},{n:'Pro',v:m.pb.Pro},{n:'Max5x',v:m.pb.Max5x},{n:'Max20x',v:m.pb.Max20x}].map(x=>({...x,p:m.total?x.v/m.total:0}))}
function renderOffers(){const rs=offerRows().filter(x=>x.v>0);let a=0,st=[];for(const r of rs){let b=a;a+=r.p*100;st.push(`${COLORS[r.n]} ${b}% ${a}%`)}document.getElementById('offerDonut').innerHTML=`<div class="donut-wrap"><div class="donut" style="background:conic-gradient(${st.join(',')||'#e8ebf0 0 100%'})"></div><div class="donut-center">${money(CURRENT.total)}</div></div><div class="legend">${rs.map(r=>`<div class="legend-row"><span class="dot" style="background:${COLORS[r.n]}"></span><span>${esc(r.n)}</span><b>${pct(r.p)}</b></div>`).join('')}</div>`}
function renderBars(){const rs=Object.values(CURRENT.bd).sort((a,b)=>b.total-a.total),mx=Math.max(1,...rs.map(x=>x.total));document.getElementById('domainBars').innerHTML=rs.map(x=>`<div class="bar-row"><span>${esc(x.d.Nom)}</span><div class="bar-track"><div class="bar-fill" style="width:${x.total/mx*100}%"></div></div><span class="num">${money(x.total)}</span></div>`).join('')}
function renderMatrix(){document.getElementById('budgetMatrix').innerHTML=Object.values(CURRENT.bd).map(x=>`<tr><td><b>${esc(x.d.Nom)}</b></td><td class="num">${money(x.seat)}</td><td class="num">${money(x.usage)}</td><td class="num">${money(x.Pro)}</td><td class="num">${money(x.Max5x)}</td><td class="num">${money(x.Max20x)}</td><td class="num"><b>${money(x.total)}</b></td><td class="num">${money(x.total*CURRENT.rate,'EUR')}</td></tr>`).join('')}
function plan(did,name){const t=D[T.tariffs].find(x=>x.Offre===name),r=CURRENT.irs.find(x=>+x.Domaine===+did&&+x.Offre===+t?.id);return{t,r,u:+r?.Nb_Utilisateurs||0}}
function renderSimulation(){DIRTY.clear();const em=Object.fromEntries(CURRENT.ers.map(r=>[r.Domaine,r]));document.getElementById('simulationBody').innerHTML=scopedDomains().map(d=>{const e=em[d.id],p=plan(d.id,'Pro'),m5=plan(d.id,'Max5x'),m20=plan(d.id,'Max20x');return`<tr data-domain="${d.id}"><td><b>${esc(d.Nom)}</b></td><td><input class="sim-input" type="number" min="0" value="${+e?.Nb_Sieges||0}" data-kind="e" data-row="${e?.id||''}" data-field="Nb_Sieges"></td><td><input class="sim-input" type="number" min="0" value="${+e?.Budget_Usage_User_Mois||0}" data-kind="e" data-row="${e?.id||''}" data-field="Budget_Usage_User_Mois"></td>${planInput(d.id,p)}${planInput(d.id,m5)}${planInput(d.id,m20)}<td class="num"><b>${money(CURRENT.bd[d.id]?.total||0)}</b></td></tr>`}).join('');document.querySelectorAll('.sim-input').forEach(i=>i.oninput=markDirty)}
function planInput(d,p){return`<td><input class="sim-input" type="number" min="0" value="${p.u}" data-kind="p" data-row="${p.r?.id||''}" data-offer="${p.t?.id||''}"></td>`}
function markDirty(e){const i=e.target,tr=i.closest('tr');tr.classList.add('pending');DIRTY.set([i.dataset.kind,i.dataset.row||'new',tr.dataset.domain,i.dataset.offer||''].join(':'),{kind:i.dataset.kind,row:+i.dataset.row||0,domain:+tr.dataset.domain,offer:+i.dataset.offer||0,value:+i.value||0,field:i.dataset.field||'Nb_Utilisateurs'})}
async function saveSimulation(){try{const a=[];for(const x of DIRTY.values()){if(x.kind==='e'){if(!x.row)throw Error('Ligne Enterprise manquante.');a.push(['UpdateRecord',T.enterprise,x.row,{[x.field]:x.value}])}else if(x.row)a.push(['UpdateRecord',T.individual,x.row,{Nb_Utilisateurs:x.value}]);else if(x.value>0)a.push(['AddRecord',T.individual,null,{Scenario:CURRENT.s.id,Domaine:x.domain,Offre:x.offer,Nb_Utilisateurs:x.value}])}if(a.length)await grist.docApi.applyUserActions(a);toast('Modifications enregistrées.');await boot()}catch(e){toast('Erreur : '+e.message,true)}}
function renderAdmin(){renderScenarios();renderTariffs();renderDomains();renderRights()}
function adminTable(title,sub,head,body,add=''){return`<article class="card"><div class="toolbar"><div><h3>${title}</h3><p>${sub}</p></div>${add}</div><div class="table-wrap"><table><thead><tr>${head.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${body}</tbody></table></div></article>`}
function inp(v,type,field,id,table,extra=''){return`<input class="admin-input" type="${type}" ${type==='checkbox'?(v?'checked':''):`value="${esc(v??'')}"`} ${extra} data-field="${field}" data-row="${id}" data-table="${table}">`}
function act(table,id){return`<div class="inline"><button class="btn small secondary save" data-table="${table}" data-row="${id}">Enregistrer</button><button class="btn small danger del" data-table="${table}" data-row="${id}">Supprimer</button></div>`}
function bindAdmin(el){el.querySelectorAll('.save').forEach(b=>b.onclick=()=>saveRow(b.closest('tr'),b.dataset.table,+b.dataset.row));el.querySelectorAll('.del').forEach(b=>b.onclick=()=>delRow(b.dataset.table,+b.dataset.row))}
async function saveRow(tr,table,id){const f={};tr.querySelectorAll('[data-field]').forEach(i=>{let v=i.type==='checkbox'?i.checked:i.value;if(i.type==='number')v=+v||0;f[i.dataset.field]=v});await grist.docApi.applyUserActions([['UpdateRecord',table,id,f]]);await boot();toast('Enregistré.')}
async function delRow(table,id){if(!confirm('Supprimer ?'))return;await grist.docApi.applyUserActions([['RemoveRecord',table,id]]);await boot();toast('Supprimé.')}
function renderScenarios(){const b=D[T.scenarios].map(s=>`<tr><td>${inp(s.Nom,'text','Nom',s.id,T.scenarios)}</td><td>${inp(s.Annee,'number','Annee',s.id,T.scenarios)}</td><td>${inp(s.Nb_Mois,'number','Nb_Mois',s.id,T.scenarios)}</td><td>${inp(s.Taux_USD_EUR,'number','Taux_USD_EUR',s.id,T.scenarios,'step="0.0001"')}</td><td>${inp(s.Taux_Utilisation,'number','Taux_Utilisation',s.id,T.scenarios,'step="0.05"')}</td><td>${act(T.scenarios,s.id)}</td></tr>`).join('');const el=document.getElementById('view-scenarios');el.innerHTML=adminTable('Scénarios','Paramètres globaux.',['Nom','Année','Mois','USD/EUR','Utilisation',''],b,`<button id="newScenario" class="btn primary">+ Nouveau</button>`);bindAdmin(el);document.getElementById('newScenario').onclick=async()=>{await grist.docApi.applyUserActions([['AddRecord',T.scenarios,null,{Nom:'Nouveau scénario',Annee:new Date().getFullYear(),Nb_Mois:12,Taux_USD_EUR:.86,Taux_Utilisation:1,Statut:'Travail',Commentaire:''}]]);await boot()}}
function renderTariffs(){const b=D[T.tariffs].map(t=>`<tr><td><b>${esc(t.Offre)}</b></td><td>${esc(t.Type_Cout)}</td><td>${inp(t.Prix_Annuel_Siege,'number','Prix_Annuel_Siege',t.id,T.tariffs)}</td><td>${inp(t.Prix_Mensuel,'number','Prix_Mensuel',t.id,T.tariffs)}</td><td>${inp(t.Actif,'checkbox','Actif',t.id,T.tariffs)}</td><td>${act(T.tariffs,t.id)}</td></tr>`).join('');const el=document.getElementById('view-tariffs');el.innerHTML=adminTable('Tarifs & offres','Référentiel des coûts.',['Offre','Type','Prix annuel','Prix mensuel','Actif',''],b);bindAdmin(el)}
function renderDomains(){const b=D[T.domains].map(d=>`<tr><td>${inp(d.Nom,'text','Nom',d.id,T.domains)}</td><td>${inp(d.Actif,'checkbox','Actif',d.id,T.domains)}</td><td>${inp(d.Responsable||'','text','Responsable',d.id,T.domains)}</td><td>${act(T.domains,d.id)}</td></tr>`).join('');const el=document.getElementById('view-domains');el.innerHTML=adminTable('Domaines','Référentiel organisationnel.',['Nom','Actif','Responsable',''],b,`<button id="newDomain" class="btn primary">+ Nouveau</button>`);bindAdmin(el);document.getElementById('newDomain').onclick=async()=>{await grist.docApi.applyUserActions([['AddRecord',T.domains,null,{Nom:'Nouveau domaine',Actif:true,Responsable:''}]]);await boot()}}
function renderRights(){const b=D[T.rights].map(r=>`<tr><td>${inp(r.Email||'','text','Email',r.id,T.rights)}</td><td><select class="admin-input" data-field="Domaine">${D[T.domains].map(d=>`<option value="${d.id}" ${+r.Domaine===+d.id?'selected':''}>${esc(d.Nom)}</option>`).join('')}</select></td><td><select class="admin-input" data-field="Role_App"><option ${r.Role_App==='Domaine'?'selected':''}>Domaine</option><option ${r.Role_App==='Admin'?'selected':''}>Admin</option></select></td><td>${inp(r.Actif,'checkbox','Actif',r.id,T.rights)}</td><td>${inp(r.Commentaire||'','text','Commentaire',r.id,T.rights)}</td><td>${act(T.rights,r.id)}</td></tr>`).join('');const el=document.getElementById('view-rights');el.innerHTML=adminTable('Droits utilisateurs','Contrôle d’accès minimaliste.',['Email','Domaine','Rôle','Actif','Commentaire',''],b,`<button id="newRight" class="btn primary">+ Ajouter</button>`);bindAdmin(el);document.getElementById('newRight').onclick=async()=>{await grist.docApi.applyUserActions([['AddRecord',T.rights,null,{Email:'',Domaine:D[T.domains][0]?.id||0,Actif:true,Role_App:'Domaine',Commentaire:''}]]);await boot()}}
